name: Release Charts
on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: aws-standalone-cp-gpu
        repository: p5ntangle/k0rdent-templates
        tag: 0.0.2
        path: templates/aws-cluster-gpu
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: aws-standalone-cp-security
        repository: p5ntangle/k0rdent-templates
        tag: 0.0.2
        path: templates/aws-standalone-cp-security
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: cluster-api-provider-aws
        repository: p5ntangle/k0rdent-templates
        tag: 1.0.5
        path: templates/cluster-api-provider-aws
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'